name: onboarding_form
description: "A new sample project for my repository"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  json_annotation: ^4.9.0
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  provider: ^6.1.2
  flutter_svg: ^2.2.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  collection:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  analyzer: ^7.6.0

  json_serializable:

flutter:

  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
